version: 0.2

phases:
   install:
      commands:
       - yum -y install make gcc
   pre_build:
      commands:
       - cd src
   build:
      commands:
       - make -j2 bin-x86_64-efi/ipxe.usb
       - make -j2 bin-x86_64-pcbios/ipxe.usb

artifacts:
   files:
    - src/bin-x86_64-efi/ipxe.usb
    - src/bin-x86_64-pcbios/ipxe.usb
   discard-paths: no
