version: 0.2

phases:
   install:
      commands:
       - yum -y update
       - yum -y install redhat-rpm-config make gcc perl mtools xz-devel
   pre_build:
      commands:
       - cd src
   build:
      commands:
       - EXTRA_CFLAGS="$RPM_OPT_FLAGS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1" EXTRA_LDFLAGS="$RPM_LD_FLAGS -specs=/usr/lib/rpm/redhat/redhat-hardened-ld" make -j2 bin-x86_64-efi/snponly.efi
       - EXTRA_CFLAGS="$RPM_OPT_FLAGS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1" EXTRA_LDFLAGS="$RPM_LD_FLAGS -specs=/usr/lib/rpm/redhat/redhat-hardened-ld" make -j2 bin-x86_64-efi/ipxe.usb
       - EXTRA_CFLAGS="$RPM_OPT_FLAGS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1" EXTRA_LDFLAGS="$RPM_LD_FLAGS -specs=/usr/lib/rpm/redhat/redhat-hardened-ld" make -j2 bin-x86_64-pcbios/undionly.kpxe
       - EXTRA_CFLAGS="$RPM_OPT_FLAGS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1" EXTRA_LDFLAGS="$RPM_LD_FLAGS -specs=/usr/lib/rpm/redhat/redhat-hardened-ld" make -j2 bin-x86_64-pcbios/ipxe.usb

artifacts:
   files:
    - src/bin-x86_64-efi/snponly.efi
    - src/bin-x86_64-efi/ipxe.usb
    - src/bin-x86_64-pcbios/undionly.kpxe
    - src/bin-x86_64-pcbios/ipxe.usb
   discard-paths: no
